kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

markdown:
  kramdown

baseurl: /w-crmint

githuburl: https://github.com/google/w-crmint/

googleanalytics: UA-127959147-1

sass:
  style: compressed
